dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: kRpJIL0ZuqXnHsdVMR8Vo955I2L2p+ZP2InUXzkPdGTn2VNrJhPcb0xtHxmy/Pnv6sZHbaG6rcYANj+AkdCa0CmedUhpCze+qF8a0P0vWh5FaVFTrHdiOZQUfFHNlpoisFd/mRpTa9MmzJBN1L8EIf0SP83Iy8r7HhXcab35sNkK5Bd/rFVUUWtucBfVpv3lmQLB5K8mDGXNxHKKHIy6md99puXfx/+CrdF7RgoiaIXZRuLJ8C0szn1LWtC3BL8/m6jh9s+Muap5ienapNohfBr8Ft/Ss4USeIvi6g6l+cOoaUfdQwzHIQMQYWFK+TfqrX8mkcsWTVw2y33mjk1HrC8QSXvfu7fiEH+nJ7frwp4JpJqERmsrFZ/9glnQigbcDTLrUhiMlqOB3l1eJ1E8/0i1rJuKdWtgOvwooHsdOdzi5inYstT2h8BeM32S9JvGpdjc+HhabuOEggYhvcbccDKRCj2YdLPHxn8EugFPZiWIqkz7ShFuY+6SDQU0Bn5aeOpLRuFmXlVNooKI4aS1JwPSjbBVCA9gcNkIMvCZLmEXK2RHTo19SKp0HmFLJsbuEAXukXkB9uV7FUgHU45P+xuBtnF+PpF6vEzE1bImxHRCrz6dQ/I+VowAtDCtptcdh/Ds32Pe1EBH6fXy0wG0SjBiXgDGtg8UgI2av2o7Oss=
