global:
  slack_api_url: 'https://hooks.slack.com/services/T6HR0TUP3/B014UA597RR/r7nR3FaDO9LTbyX'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
    - channel: '#kosntantin_kostenko'
